name: PR File Change Notification

on: pull_request

jobs:
  file-change-check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0 # Ensures all history is fetched

      - name: Count files changed
        run: |
          echo "FILE_COUNT=$(git diff --name-only ${{ github.event.pull_request.base.sha }} ${{ github.event.pull_request.head.sha }} | wc -l)" >> $GITHUB_ENV

      - name: Notify Slack if threshold exceeded
        if: ${{ env.FILE_COUNT > 30 }}
        uses: rtCamp/action-slack-notify@v2
        env:
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK_URL }}
          SLACK_COLOR: "#FF0000"
          SLACK_MESSAGE: "A PR with more than 30 file changes was submitted. Please review it for in-person discussion."
          SLACK_TITLE: "High File Change PR Alert"
